[package]
name = "kync"
version = "0.1.0"
authors = ["KizzyCode <development@kizzycode.de>"]
edition = "2018"


[dependencies]
libloading = "0.5.0"

[dev-dependencies]
test_plugin = { path = "./test_plugin" }


[profile.release]
overflow-checks = true

[profile.bench]
overflow-checks = true