[package]
name = "test_plugin"
version = "0.1.0"
authors = ["KizzyCode <development@kizzycode.de>"]
edition = "2018"


[lib]
name = "test_plugin"
crate-type = ["dylib"]


[dependencies]


[profile.release]
overflow-checks = true

[profile.bench]
overflow-checks = true